baseURL: https://estelletessaro-portfolio.netlify.app/
languageCode: en-us
title: Estelle
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: More about me
    subtitle: |-
      Hi! Welcome to my personal site. I blog about the things I learn, 
      mostly in R and python, and you can find my latest work below.
    title: Estelle Tessaro
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: etessaro.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +32 123 45 67 89
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Estelle
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/estelle.tessaro/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/estelletessaro/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/estelletessaro/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/estelletessaro/
  image: ''
  name: Your name
  navigation:
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/aboutme
      - name: Portfolio
        url: blogs
    menu: Menu
    subtitle: 
    title: Estelle
  tiles:
    enable: yes
    showcase:
      - image: sunset.jpg
        subtitle: About Me
        title: I love sunsets
        url: blogs/aboutme
      - image: genderdiscrimination.jpg
        subtitle: Homework 3
        title: Pay Discrimination - Omega
        url: blogs/homework3
      - image: germany.jpg
        subtitle: Homework 1A
        title: Opinion Polls for 2021 German Elections
        url: blogs/homework1a
      - image: biden.jpg
        subtitle: Homework 2A
        title: Biden's Approval Margins
        url: blogs/homework2a
      - image: wine.jpg
        subtitle: Homework 1B
        title: Where People Drink the Most Wine, Beer & Spirits
        url: blogs/homework1b
      - image: londonbike.jpg
        subtitle: Homework 2B
        title: London Bike Rentals over Time
        url: blogs/homework2b

  two:
    buttonText: My CV
    enable: yes
    subtitle: "Find more details of my early-career and education experiences below."
    title: Learn more about me
    url: blogs/mycv
